### ISSUE TITLE
Songs problem with CI3

### ISSUE THREAD

**Issue by uno-de-piera** [cgarciagl/Yupii#2]
Hi,

FIrst congrats for this project, its great.

I tested with CI2.X without issues, but in CI3 when I make the songs controller received an error:

An error ocurrer on server, please try again in a minute.

¿You know which is the problem?

Thanks.

**Comment by cgarciagl** [comment]
Hi Israel, 

I had fixed some issues with CI3 in the last versión of Yupii, please update your version (downloading it again from github), and check it, and if after updating you still have problems please let me know.

 when the user sees the message "An error ocurred on server, please try again in a minute.", the real error in the server is showed in the browser's console, so please check what is the error in the console and i'll try to figure it out.

Thank you for testing Yupii, Cheers!

PD. puedes escribirme en Español a mi correo personal cgarciagl en gmail por algún detalle :)

Saludos
