### ISSUE TITLE
DataTable display problem

### ISSUE THREAD

**Issue by okoos** [cgarciagl/Yupii#3]
Hi,

When I disable uppercase option from yupii config and insert artist name as "Müslüm Gürses"  this string display normaly on edit form also phpmyadmin interface but when I select Table tab and goto this record on DataTable, this string display as "Muesluem Guerses" ü=ue.
how can I solve this problem?

regards

**Comment by cgarciagl** [comment]
Thanx... is fixed now on the Repo :+1:

 just update
