### ISSUE TITLE
Falta documentación y ejemplos.

### ISSUE THREAD

**Issue by SaulSalazarMendez** [cgarciagl/Yupii#4]
Hola, 
Soy estudiante de Informática dentro de la UV, el Revo me recomendo usar Yuppi para un proyecto. En un principio me parecia exelente Yuppi pero cuando quize realizar una personalización de la vistas que generaba me encontre con un muro que no pue cruzar, revise tu código para ver si podia modificarlo pero la verdad no lo logre entender.
Yupii me parece un proyecto muy interezante, sin embargo, esta verde para utilizarce como herrameinta de desarrollo.Si existieran más documentación o almenos más ejemplos de como usar la librería creo que sería más popular dentro de la comunidad de codeigniter.
Yo podría ayudar en el proyecto, pero primero necesito entender el código.

Nota1: Lo que deseaba hacer era desabilitar los reportes, la edición y hacer busquedas personalizadas para generar reportes.

Nota2: Es cierto que tu codigo esta documentado pero le falta más, genere la documentación con doxygen y la verda esta muy limitada.

Nota3: escribo esto aqui dado que no puede encontrar tu correo.

**Comment by cgarciagl** [comment]
Que tal Saul,

Me alegra mucho que estés utilizando Yupii en tu proyecto, y aún más que
estés dispuesto a colaborar en este asunto.

Como bien dices falta agregar documentación al proyecto con ejemplos
concretos más específicos. Te comento que yo ahora utilizo Yupii en todas
las aplicaciones que tengo en producción, que son de diferentes tipos y me
está funcionando muy bien. Todo esto que quieres hacer en realidad es muy
simple de hacerlo solo que falta documentar como se hace.

Esta semana estoy en la ciudad de Mérida Yucatán en un congreso presentando
precisamente algunos proyectos que he realizado utilizando Yupii como base,
regreso este miércoles por la tarde, si te parece podríamos reunirnos el
jueves o viernes para mostrarte ejemplos que tengo sobre esto que deseas
hacer, e incluso te puedo proporcionar algunos proyectos de ejemplo que
pueden servirte dependiendo de la naturaleza de tu proyecto.

Un saludo y estamos en contacto

Carlos G
